HEROES = {
    # strength
    "Alchemist": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Axe": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Bristleback": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Centaur": {"attribute": "strength", "complexity": "easy", "position": "5", "type_of_battle": "melee"},
    "Chaos_knight": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Dawnbreaker": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Doom": {"attribute": "strength", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Dragon_knight": {"attribute": "strength", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Earth_spirit": {"attribute": "strength", "complexity": "hard", "position": "5", "type_of_battle": "melee"},
    "Earthshaker": {"attribute": "strength", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Elder_titan": {"attribute": "strength", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Huskar": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Kunkka": {"attribute": "strength", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Legion_commander": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Life_stealer": {"attribute": "strength", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Mars": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Night_stalker": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Ogre_magi": {"attribute": "strength", "complexity": "easy", "position": "5", "type_of_battle": "melee"},
    "Omniknight": {"attribute": "strength", "complexity": "easy", "position": "5", "type_of_battle": "melee"},
    "Primal_beast": {"attribute": "strength", "complexity": "easy", "position": "5", "type_of_battle": "melee"},
    "Pudge": {"attribute": "strength", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Slardar": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Spirit_breaker": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Sven": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Tidehunter": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Tiny": {"attribute": "strength", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Treant": {"attribute": "strength", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Tusk": {"attribute": "strength", "complexity": "easy", "position": "5", "type_of_battle": "melee"},
    "Underlord": {"attribute": "strength", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Undying": {"attribute": "strength", "complexity": "easy", "position": "5", "type_of_battle": "melee"},
    "Skeleton_king": {"attribute": "strength", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    # agility
    "Antimage": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Arc_warden": {"attribute": "agility", "complexity": "hard", "position": "1", "type_of_battle": "range"},
    "Bloodseeker": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Bounty_hunter": {"attribute": "agility", "complexity": "easy", "position": "5", "type_of_battle": "melee"},
    "Clinkz": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Drow_ranger": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Ember_spirit": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Faceless_void": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Gyrocopter": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Hoodwink": {"attribute": "agility", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Juggernaut": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Luna": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Medusa": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Meepo": {"attribute": "agility", "complexity": "hard", "position": "1", "type_of_battle": "melee"},
    "Monkey_king": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Morphling": {"attribute": "agility", "complexity": "hard", "position": "1", "type_of_battle": "range"},
    "Naga_siren": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Phantom_assassin": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Phantom_lancer": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Razor": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Riki": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Nevermore": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Slark": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Sniper": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Spectre": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Templar_assassin": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Terrorblade": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Troll_warlord": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Ursa": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Viper": {"attribute": "agility", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Weaver": {"attribute": "agility", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    # intellect
    "Apparition": {"attribute": "intellect", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Crystal_maiden": {"attribute": "intellect", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Death_prophet": {"attribute": "intellect", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Disruptor": {"attribute": "intellect", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Enchantress": {"attribute": "intellect", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Grimstroke": {"attribute": "intellect", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Jakiro": {"attribute": "intellect", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Keeper_of_the_light": {"attribute": "intellect", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Leshrac": {"attribute": "intellect", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Lich": {"attribute": "intellect", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Lina": {"attribute": "intellect", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Lion": {"attribute": "intellect", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Muerta": {"attribute": "intellect", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Furion": {"attribute": "intellect", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Necrolyte": {"attribute": "intellect", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    "Oracle": {"attribute": "intellect", "complexity": "hard", "position": "5", "type_of_battle": "range"},
    "Outworld_desroyer": {"attribute": "intellect", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Puck": {"attribute": "intellect", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Pugna": {"attribute": "intellect", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Queenofpain": {"attribute": "intellect", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Rubick": {"attribute": "intellect", "complexity": "hard", "position": "5", "type_of_battle": "range"},
    "Shadow_demon": {"attribute": "intellect", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Shadow_shaman": {"attribute": "intellect", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Silencer": {"attribute": "intellect", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Skywrath_mage": {"attribute": "intellect", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Storm_spirit": {"attribute": "intellect", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Tinker": {"attribute": "intellect", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Warlock": {"attribute": "intellect", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Witch_doctor": {"attribute": "intellect", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Zeus": {"attribute": "intellect", "complexity": "easy", "position": "1", "type_of_battle": "range"},
    # universal
    "Abaddon": {"attribute": "universal", "complexity": "easy", "position": "1", "type_of_battle": "melee"},
    "Bane": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Batrider": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Beastmaster": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Brewmaster": {"attribute": "universal", "complexity": "hard", "position": "1", "type_of_battle": "melee"},
    "Broodmother": {"attribute": "universal", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Chen": {"attribute": "universal", "complexity": "hard", "position": "5", "type_of_battle": "range"},
    "Clockwerk": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Dark_seer": {"attribute": "universal", "complexity": "easy", "position": "5", "type_of_battle": "melee"},
    "Dark_willow": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Dazzle": {"attribute": "universal", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Enigma": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Invoker": {"attribute": "universal", "complexity": "hard", "position": "1", "type_of_battle": "range"},
    "Wisp": {"attribute": "universal", "complexity": "hard", "position": "5", "type_of_battle": "range"},
    "Lone_druid": {"attribute": "universal", "complexity": "hard", "position": "1", "type_of_battle": "range"},
    "Lycan": {"attribute": "universal", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Magnus": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Marci": {"attribute": "universal", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Mirana": {"attribute": "universal", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Nyx_assassin": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Pangolier": {"attribute": "universal", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Phoenix": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Sand_king": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Snapfire": {"attribute": "universal", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Techies": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "Timbersaw": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "melee"},
    "Vengefulspirit": {"attribute": "universal", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Venomancer": {"attribute": "universal", "complexity": "easy", "position": "5", "type_of_battle": "range"},
    "Visage": {"attribute": "universal", "complexity": "hard", "position": "5", "type_of_battle": "range"},
    "Void_spirit": {"attribute": "universal", "complexity": "medium", "position": "1", "type_of_battle": "melee"},
    "Windrunner": {"attribute": "universal", "complexity": "medium", "position": "1", "type_of_battle": "range"},
    "Winter_wyvern": {"attribute": "universal", "complexity": "medium", "position": "5", "type_of_battle": "range"},
    "None": {"attribute": "none", "complexity": "none", "position": "123", "type_of_battle": "none"}
    }

QUESTIONS = {
    "1": {"text": "Чем вам интереснее заниматься в игре"},
    "2": {"text": "Сколько часов вы готовы потратить на изучение персонажа?"},
    "3": {"text": "Охарактеризуйте себя"},
    "4": {"text": "Какой тип боя вы предпочитаете?"}
}